const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    GET_POSTS: 'GET_POSTS',
    GET_PRICE_RANGE: 'GET_PRICE_RANGE',
    GET_ACREAGE_RANGE: 'GET_ACREAGE_RANGE'
}

export default actionTypes;